# Generated by Django 4.0.4 on 2022-05-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
